/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */
/* $Id$ */

#ifndef _displayTask_h
#define _displayTask_h

#include <cisstMultiTask.h>
#include "displayUI.h"

class displayTask: public mtsTaskPeriodic {
    // set log level to 5
    CMN_DECLARE_SERVICES(CMN_NO_DYNAMIC_CREATION, 5);
    volatile bool ExitFlag;
    double StartValue;
    
 protected:
    // local copy of data used in commands
    cmnDouble Data;
    cmnDouble AmplitudeData;
    mtsStateIndex StateIndex;
#ifdef CISST_GETVECTOR
    mtsVector<cmnDouble> DataVec;
#endif

    struct {
       // functions which will be bound to commands
       mtsFunctionRead GetData;
       mtsFunctionRead GetStateIndex;
#ifdef CISST_GETVECTOR
       mtsFunctionQualifiedRead GetDataVector;
#endif
       mtsFunctionWrite SetAmplitude;
    } Generator;

    // user interface generated by FTLK/fluid
    displayUI UI;
    
 public:
    // see sineTask.h documentation
    displayTask(const std::string & taskName, double period);
    ~displayTask() {};
    void Configure(const std::string & CMN_UNUSED(filename) = "");
    void Startup(void);
    void Run(void);
    void Cleanup(void) {};
    bool GetExitFlag (void) { return ExitFlag;}
};

CMN_DECLARE_SERVICES_INSTANTIATION(displayTask);

#endif // _displayTask_h

/*
  Author(s):  Ankur Kapoor, Peter Kazanzides, Anton Deguet
  Created on: 2004-04-30

  (C) Copyright 2004-2008 Johns Hopkins University (JHU), All Rights
  Reserved.

--- begin cisst license - do not edit ---

This software is provided "as is" under an open source license, with
no warranty.  The complete license can be found in license.txt and
http://www.cisst.org/cisst/license.txt.

--- end cisst license ---

*/
