/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */
/* $Id: displayTask.h 1030 2010-01-07 06:40:36Z pkazanz1 $ */

#ifndef _displayTask_h
#define _displayTask_h

#include <cisstMultiTask.h>
#include "displayUI.h"

// FLTK 
// Has 
class displayTask: public mtsTaskPeriodic {
    // set log level to "Run Error"
    CMN_DECLARE_SERVICES(CMN_NO_DYNAMIC_CREATION, CMN_LOG_LOD_RUN_ERROR);
    
 protected:
    // local copy of data used in commands
    double Data;
    mtsDouble AmplitudeData;

    // for provided interface 
    mtsDouble aDouble; 
    mtsDoubleVec aVector; 
    mtsDoubleFrm4x4 aFrm4x4;

    bool dataChanged; 

    void AddDouble(const mtsDouble & added); 
    void ZeroAll(void); 
    void SetFrm(const mtsDoubleFrm4x4 & frm4x4); 

    // for required interface 
    struct {
       // functions which will be bound to commands
       mtsFunctionRead GetData;
       mtsFunctionWrite SetAmplitude;
    } Generator;

    // user interface generated by FTLK/fluid
    displayUI UI;
    
 public:
    // see sineTask.h documentation
    displayTask(const std::string & taskName, double period);
    ~displayTask() {};
    void Configure(const std::string & CMN_UNUSED(filename) = "");
    void Startup(void);
    void Run(void);
    void Cleanup(void) {};
};

CMN_DECLARE_SERVICES_INSTANTIATION(displayTask);

#endif // _displayTask_h 
