/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */

/*
  $Id: mtsMonitorFilterBase.h 3034 2011-10-09 01:53:36Z adeguet1 $

  Author(s):  Min Yang Jung
  Created on: 2012-01-07

  (C) Copyright 2004-2012 Johns Hopkins University (JHU), All Rights Reserved.

  --- begin cisst license - do not edit ---

  This software is provided "as is" under an open source license, with
  no warranty.  The complete license can be found in license.txt and
  http://www.cisst.org/cisst/license.txt.

  --- end cisst license ---
*/

/*!
  \file
  \brief Defines the base class of filters that are used for fault detection and 
         diagnosis
*/

#ifndef _mtsMonitorFilterBase_h
#define _mtsMonitorFilterBase_h

#include <cisstCommon/cmnGenericObject.h>
#include <cisstMultiTask/mtsStateTable.h>

#include <vector>
#include <iostream>
#include <sstream>

/*!
  \ingroup cisstMultiTask
*/

class mtsStateTable;

class mtsMonitorFilterBase : public cmnGenericObject
{
public:
    /*! Names of input signals.  A filter may need more than one signal to run 
        its filtering algorithm. */
    class SignalElement {
    protected:
        std::string Name;
        mtsStateDataId StateDataId;
    public:
        // MJ TEMP: Use only one output of type double for now.  Can be extended to 
        // arbitrary type later
        double Placeholder;

        SignalElement() : Name("NONAME"), Placeholder(0.0) {}
        SignalElement(const std::string & name) : Name(name), Placeholder(0.0) {}

        const std::string & GetName(void) const { return Name; }
        inline mtsStateDataId GetStateDataId(void) const { return StateDataId; }
        inline void SetStateDataId(mtsStateDataId id)  { StateDataId = id; }
    };

    typedef std::vector<SignalElement*> SignalElementsType;
    typedef std::vector<std::string> SignalNamesType;

private:    
    /*! ID of this filter, which is unique within the process.  This allows multiple 
        filters of the same type to be used in the same state table.  */
    static int UID;

protected:
    /*! UID of this filter */
    int FilterUID;

    /*! Name of this filter.  Set by derived filter */
    const std::string FilterName;

    /*! If this filter is active */
    bool Enabled;

    /*! Instance of state table that this filter is attached to */
    mtsStateTable * StateTable;

    /*! Input signals required by this filter */
    SignalElementsType InputSignals;

    /*! Output signals that this filter generates */
    SignalElementsType OutputSignals;

    /*! Helper function to add input signal to this filter */
    bool AddInputSignal(const std::string & signalName);
    /*! Helper function to add output signal generated by filter */
    bool AddOutputSignal(const std::string & signalName);

public:
    /*! Constructors and destructor */
    mtsMonitorFilterBase(void); 
    mtsMonitorFilterBase(const std::string & filterName);
    virtual ~mtsMonitorFilterBase();

#if 0 // MJ: future improvements
    /*! Add input signal to this filter.  A placeholder of appropriate type 
        is created internally to fetch new values from the state table. */
    bool AddInput(const std::string & componentName, const std::string & signalName);
    // TODO: push_back (name), prepare placeholder to fetch new input values from state table

    // TODO: add an option to add this output to standardized provided interface (if filter is
    // attached to the source component and monitoring component wants to fetch the output
    // values, this feature is required)
    bool AddOutput(const std::string & signalName); 
#endif
    /*! Core filtering function */
    virtual void DoFiltering(void) = 0;

    /*! Getters and setters */
    //@{
    inline int GetFilterUID(void) const {
        return FilterUID;
    }
    inline const std::string & GetFilterName(void) const {
        return this->FilterName;
    }

    inline bool IsEnabled(void) const {
        return this->Enabled;
    }
    inline void Enable(bool enable = true) {
        this->Enabled = enable;
    }

    inline size_t GetNumberOfInputs(void) const {
        return InputSignals.size();
    }
    inline size_t GetNumberOfOutputs(void) const {
        return OutputSignals.size();
    }

    SignalNamesType GetInputSignalNames(void) const;
    SignalNamesType GetOutputSignalNames(void) const;

    SignalElement * GetInputSignal(size_t index) const;
    SignalElement * GetOutputSignal(size_t index) const;

    inline void SetStateTableInstance(mtsStateTable * stateTable) {
        StateTable = stateTable;
    }
    //@}

    /*! To support human readable outputs (for debugging purpose) */
    virtual std::string ToString(void) const  {
        std::stringstream ss;
        ToStream(ss);
        return ss.str();
    };
    virtual void ToStream(std::ostream & outputStream) const = 0;

};

inline std::ostream & operator << (std::ostream & outputStream, const mtsMonitorFilterBase & filter)
{
    filter.ToStream(outputStream);
    return outputStream;
}

#endif // _mtsMonitorFilterBase_h

