/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-    */
/* ex: set filetype=cpp softtabstop=4 shiftwidth=4 tabstop=4 cindent expandtab: */

/*
  $Id: mtsMonitorFilterBase.h 3034 2011-10-09 01:53:36Z adeguet1 $

  Author(s):  Min Yang Jung
  Created on: 2012-01-07

  (C) Copyright 2004-2012 Johns Hopkins University (JHU), All Rights Reserved.

  --- begin cisst license - do not edit ---

  This software is provided "as is" under an open source license, with
  no warranty.  The complete license can be found in license.txt and
  http://www.cisst.org/cisst/license.txt.

  --- end cisst license ---
*/

/*!
  \file
  \brief Defines the base class of filters that are used for fault detection and 
         diagnosis
*/

#ifndef _mtsMonitorFilterBase_h
#define _mtsMonitorFilterBase_h

#include <cisstCommon/cmnGenericObject.h>
#include <cisstMultiTask/mtsStateTable.h>

#include <vector>
#include <iostream>
#include <sstream>

/*!
  \ingroup cisstMultiTask
*/

class mtsStateTable;

class mtsMonitorFilterBase : public cmnGenericObject
{
public:
    /*! Type of filter */
    typedef enum {
        INVALID,        // invalid filter is not processed
        FEATURE,        // =f(measurement)
        FEATURE_VECTOR, // =sum_of(FEATURE)
        SYMPTOM,        // =f(FEATURE_VECTOR) 
        SYMPTOM_VECTOR  // =sum_of(SYMPTOM)
    } FILTER_TYPE;

    typedef double PlaceholderType;
    typedef mtsDoubleVec PlaceholderVectorType;

    /*! Names of input signals.  A filter may need more than one signal to run 
        its filtering algorithm. */
    class SignalElement {
    public:
        typedef enum { SCALAR, VECTOR } SIGNAL_TYPE;
    protected:
        std::string Name;
        mtsStateDataId StateDataId; // typedefed as int
        SIGNAL_TYPE SignalType;
    public:
        PlaceholderType Placeholder;
        PlaceholderVectorType PlaceholderVector;

        SignalElement() : Name("NONAME"), 
                          StateDataId(mtsStateTable::INVALID_STATEVECTOR_ID), 
                          SignalType(SCALAR),
                          Placeholder(0.0) {}
        SignalElement(const std::string & name, SIGNAL_TYPE type) 
            : Name(name), 
              StateDataId(mtsStateTable::INVALID_STATEVECTOR_ID), 
              SignalType(type),
              Placeholder(0.0) {}

        const std::string & GetName(void) const { return Name; }
        inline mtsStateDataId GetStateDataId(void) const { return StateDataId; }
        inline void SetStateDataId(mtsStateDataId id) { StateDataId = id; }
    };

    typedef std::vector<SignalElement*> SignalElementsType;
    typedef std::vector<std::string> SignalNamesType;

private:    
    /*! ID of this filter, which is unique within the process.  This allows multiple 
        filters of the same type to be used in the same state table.  */
    static int UID;

protected:
    typedef mtsMonitorFilterBase BaseType;

    /*! UID of this filter */
    int FilterUID;
    /*! Type of this filter */
    const FILTER_TYPE FilterType;
    /*! Name of this filter.  Set by derived filter */
    const std::string FilterName;
    /*! If this filter is active */
    bool Enabled;
    /*! Instance of state table that this filter is attached to */
    mtsStateTable * StateTable;

    /*! Input signals required by this filter */
    SignalElementsType InputSignals;
    /*! Output signals that this filter generates */
    SignalElementsType OutputSignals;

    /*! Helper function to add input signal to this filter */
    bool AddInputSignal(const std::string & signalName, BaseType::SignalElement::SIGNAL_TYPE signalType);
    /*! Helper function to add output signal generated by filter */
    bool AddOutputSignal(const std::string & signalName, BaseType::SignalElement::SIGNAL_TYPE signalType);

public:
    /*! Constructors and destructor */
    mtsMonitorFilterBase(void); 
    mtsMonitorFilterBase(FILTER_TYPE filterType, const std::string & filterName);
    virtual ~mtsMonitorFilterBase();

#if 0 // MJ: future improvements
    /*! Add input signal to this filter.  A placeholder of appropriate type 
        is created internally to fetch new values from the state table. */
    bool AddInput(const std::string & componentName, const std::string & signalName);
    // TODO: push_back (name), prepare placeholder to fetch new input values from state table

    // TODO: add an option to expose an output to the standardized provided interface.
    // This can be useful if the monitoring component wants to fetch output values when a filter 
    // is attached to the source component.
    bool AddOutput(const std::string & signalName); 
#endif
    /*! Core filtering function */
    virtual void DoFiltering(bool debug = false) = 0;

    /*! Getters and setters */
    //@{
    inline int GetFilterUID(void) const {
        return FilterUID;
    }
    inline const std::string & GetFilterName(void) const {
        return this->FilterName;
    }

    inline bool IsEnabled(void) const {
        return this->Enabled;
    }
    inline void Enable(bool enable = true) {
        this->Enabled = enable;
    }

    inline size_t GetNumberOfInputs(void) const {
        return InputSignals.size();
    }
    inline size_t GetNumberOfOutputs(void) const {
        return OutputSignals.size();
    }

    std::string GetInputSignalName(size_t index, bool withUID = false) const;
    std::string GetOutputSignalName(size_t index, bool withUID = false) const;

    SignalNamesType GetInputSignalNames(void) const;
    SignalNamesType GetOutputSignalNames(void) const;

    // MJ: returns reference instead???
    SignalElement * GetInputSignalElement(size_t index) const;
    SignalElement * GetOutputSignalElement(size_t index) const;

    inline void SetStateTableInstance(mtsStateTable * stateTable) {
        StateTable = stateTable;
    }
    //@}

    /*! To support human readable outputs (for debugging purpose) */
    virtual std::string ToString(void) const  {
        std::stringstream ss;
        ToStream(ss);
        return ss.str();
    };
    virtual void ToStream(std::ostream & outputStream) const = 0;

};

inline std::ostream & operator << (std::ostream & outputStream, const mtsMonitorFilterBase & filter)
{
    filter.ToStream(outputStream);
    return outputStream;
}

#endif // _mtsMonitorFilterBase_h

