name: macOS 13

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4

    - name: Download cisstNetlib
      run: |
        cmake -E make_directory ${{github.workspace}}/cisstNetlib-build
        git clone https://github.com/jhu-cisst/cisstNetlib ${{github.workspace}}/cisstNetlib-source

    - name: Build cisstNetlib
      working-directory: ${{github.workspace}}/cisstNetlib-build
      run: |
        cmake ${{github.workspace}}/cisstNetlib-source -DcisstNetlib_LANGUAGE=C
        cmake --build . --config Release
        sudo cmake --build . --target install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -C ${{github.workspace}}/.github/workflows/cmake-macos-cache.cmake

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        source cisstvars.sh
        cmake --build . --config Release

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   shell: bash
    #   run: |
    #     source cisstvars.sh
    #     cisstCommonTests -r
    #     cisstVectorTests -r
    #     cisstNumericalTests -r
    #     cisstOSAbstractionTests -r
    #     cisstParameterTypesTests -r
